server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://101.132.165.5:3306/forklift?useUnicode=true&amp&serverTimezone=UTC&characterEncoding=utf-8
    username: forklift
    password: fl#DB1qazxsw2

mybatis:
  mapper-locations: classpath:mybatis/mapper/standard/*.xml  # 注意:一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.duoblock.mybatisdemo.entity.po  # 注意:对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true # 数据库字段下划线自动转驼峰
